[package]
name = "clnaddress"
version = "0.1.5"
edition = "2024"
rust-version = "1.85.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = "0.8"
log = "0.4"

cln-plugin = "0.7"
# cln-plugin = { path = "../lightning/plugins/", version = "^0.6" }
cln-rpc = "0.7"
# cln-rpc = { path = "../lightning/cln-rpc/", version = "^0.6" }

bech32 = "0.12"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["fs", "sync", "rt-multi-thread"] }
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
# nostr = { git = "https://github.com/rust-nostr/nostr.git", rev = "ff5be7d1416ea201887a02f648795010a3cbdf49" }
# nostr-sdk = { git = "https://github.com/rust-nostr/nostr.git", rev = "ff5be7d1416ea201887a02f648795010a3cbdf49" }
nostr = { version = "0.45.1" }
nostr-sdk = { version = "0.45.1" }
parking_lot = "0.12"

[profile.optimized]
inherits = "release"
panic = "abort"
strip = true
codegen-units = 1
lto = "fat"
debug = false
